workflows:
  android-workflow:
    name: Build Android
    max_build_duration: 60
    environment:
      vars:
        SUPABASE_URL: https://zckpocoedkulokcpxvqu.supabase.co
        SUPABASE_KEY: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpja3BvY29lZGt1bG9rY3B4dnF1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwNzE4ODMsImV4cCI6MjA2OTY0Nzg4M30.3HdOMxvIqSnkPFxpUAOrCLXIba3G9Wo95VMxSE_BqUs

    scripts:
      - name: Build APK
        script: ./gradlew assembleDebug

    artifacts:
      - app/build/outputs/apk/debug/app-debug.apk
